version: '3.8'

services:
  mongo:
    container_name: web-crawler-db
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: web-crawler
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    driver: local
